**用错误处理代码来处理预期会发生的状况，用断言来处理绝不应该发生的状况**

错误处理通常用来检查有害的输入数据，而断言是用于检查代码中的bug
举例说明：如果一个类对象在另一个类中声明，在一个函数中使用，可以在该函数中使用断言检查该类对象有没有实例化。所以说断言是用来检查代码的bug，而不是用来检查运行时的错误输入。

断言可以用于处理代码中不应发生的错误（代码bug），错误处理技术用来处理预料中可能要发生的错误。

**对于高健壮的代码，应该先使用断言再处理错误**
有点难理解

## 错误处理技术
处理错误最恰当的方式要根据出现错误的软件的类型而定，错误处理方式有时更侧重于正确性，而有时更侧重于健壮性。

## 异常
异常是把代码中的错误或异常事件传递给调用方代码的一种特殊手段。如果在一个子程序中遇到了预料之外的情况，但不知道怎么处理它，就可以抛出一个异常。    
异常的应用场景跟断言相似--都是用来处理那些不罕见甚至永远不该发生的情形。    
调用子程序的代码需要了解被调用代码中可能会抛出的异常，因此异常弱化了封装性。    

错误处理技术用于检查错误的用户输入，断言用于检查代码错误，那异常用于检查什么？

对于异常可以从两方面进行考虑：
* 什么时机需要抛出异常:定义自己的异常类（在适当的抽象层次抛出异常）
* 什么时机需要捕获异常:了解所用函数库可抛出的异常

# 分享会的一些观点
1. 私有方法不捕获异常，公有方法中才捕获异常；因为用户永远也不可能直接调用私有方法，在公共接口中做好捕获防护就够了。
2. try...catch异常处理结构中，catch结构一定不能为空（除非特殊情况，要注释说明），不然永远也不知道哪里抛出了异常。
3. 抛出异常的时机：    

* 当一些错误（输入或代码造成）影响了整个软件的功能，导致软件不能正常使用，就应该抛出异常。
* 只有在真正例外的情况下才抛出异常    
例如：端口保护的配置文件读取过程中，文件内容格式错误是预料之中的，就不抛异常，通过提示或者日志来处理错误；但如果配置文件损坏，则抛出异常。

4. 捕获并处理异常    
* 如果捕获异常的地方没有能力正确地处理异常，需要重新抛出异常。（只有当不知道如何处理时，就应该抛出异常）     
例：Phoenix在初始化的的过程中，在最后UI的地方来了一个try...catch。不在里面有太多的try...catch结构。是因为即便在catch中写了一条日志，也不能够保证这是正确处理了异常，即保证软件不崩，能够正常使用，对接下来的运行不影响。所以即便里面的catch中写了一条日志，也要重新抛出异常。
* 对第三方函数库的调用一定要使用try...catch结构，前提是要了解函数库会抛出哪些异常。

5. 考虑一个集中的异常报告机制
